### ISSUE TITLE
Deprecation of functions cause errors in other plugins/themes

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-simple-sidebars#22] opened 2017-03-08 14:18 UTC
@nathanrice I'm not sure how we should handle this, but the changes in this plugin are going to cause some issues.

For instance, if you use Genesis connect for WooCommerce, you'll end up with the Simple Sidebar above the default sidebar along with a notice:

> Notice: ss_do_one_sidebar is deprecated since version 2.1.0 with no alternative available. in /home/dreamwhi/public_html/dev8/wp-includes/functions.php on line 3832

![ss-notice](https://cloud.githubusercontent.com/assets/1271053/23707340/fbf77c6e-03df-11e7-9642-10f88f0e6a94.png)

Note that this shows up on all pages, not just product pages.

There are quite a few tutorials out there along with custom themes that would be using things like `remove_action( 'genesis_sidebar', 'ss_do_sidebar' );`

**Comment by nathanrice** [comment] 2017-03-08 15:08
OK, we'll save this release for last, then.

Most plugins we release don't have dependency/modification problems. So we don't usually have to deal with formal deprecation, and accounting for people messing with hooked functions, etc.

But Sidebars is different. Obviously, people want to move their sidebars around sometimes, and to make that compatible with Simple Sidebars, they have to mess with the hooked functions in this plugin too.

I think I have an idea for accounting for this. It would be to use the [same method I used to inject the custom sidebar into the header](https://github.com/copyblogger/genesis-simple-sidebars/blob/develop/includes/class-genesis-simple-sidebars-core.php#L68-L74). It will still throw the deprecated notice, but as long as they're moving the Genesis sidebar functions along with the Simple Sidebars functions, they should get the results they're looking for. And since deprecated notices only show when WP_DEBUG is true, we should be OK to release the update.

**Comment by nathanrice** [comment] 2017-03-09 04:10
OK, I've switched the swap methods, and reduced a whole bunch of code too. Because I'm directly hijacking the widget output itself, users should now be able to move stuff around in Genesis without any negative impact or requiring any special techniques unique to GSS.

Give this the normal use test and report any weirdness.

**Comment by nickcernis** [comment] 2017-03-09 14:51
With 7b439c9 I'm still seeing a doubled primary sidebar if Genesis Connect for WooCommerce is active:

<img width="458" alt="test_content" src="https://cloud.githubusercontent.com/assets/647669/23754814/40aad24c-04d6-11e7-99d3-1f72164e1fd9.png">

I don't see that in the master branch:

<img width="448" alt="test_content" src="https://cloud.githubusercontent.com/assets/647669/23754847/5fe81db8-04d6-11e7-8125-896cb78fad8d.png">

Test condition:

- Genesis Sample active.
- WooCommerce and Genesis Connect for WooCommerce active.
- Post layout set to content-sidebar.
- SS settings set to Default in Header, Primary, and Secondary.
- WP_DEBUG disabled.

I get the deprecation notice between the duplicated sidebars only if WP_DEBUG is on, but that part was expected. (Guessing we also need an issue to update Genesis Connect to drop the deprecated sidebar functions once this update goes live?)

I think developers will be okay with the deprecation notices if we can offer guidance as to what they need to update in their plugins, but regular customers may complain about the doubled sidebar output.

![screencapture-wptest-dev-2017-03-02-test-content-1489070806738](https://cloud.githubusercontent.com/assets/647669/23755161/5ec87350-04d7-11e7-9f2f-11ef4d906da4.png)

cc @nathanrice @dreamwhisper

**Comment by dreamwhisper** [comment] 2017-03-09 16:15
> I think developers will be okay with the deprecation notices if we can offer guidance as to what they need to update in their plugins, but regular customers may complain about the doubled sidebar output.

The double sidebar output is going to cause a lot of issues for customers. I also agree that we should offer some guidance regarding the notice in the form of a wiki or in our KB.

**Comment by nathanrice** [comment] 2017-03-09 18:57
@nickcernis @dreamwhisper I'm looking into it.

**Comment by nathanrice** [comment] 2017-03-10 15:27
Question: are we just accounting for the method used in GWC? We can release an update to GWC, thankfully, but if other methods are being uses/promoted out there, I'd like to know about them so I can test against them too.

**Comment by nickcernis** [comment] 2017-03-10 16:30
The Genesis Connect method is the main one that will cause doubled sidebars.

Likely affected users are:

1. Those who unhook the Simple Sidebars to add their own sidebar, without also unhooking the main Genesis sidebar (why Genesis Connect for Woo sees doubled sidebars).

    For example, this will result in a doubled sidebar as things stand:

    ~~~php
    remove_action( 'genesis_sidebar', 'ss_do_sidebar' );
    remove_action( 'genesis_sidebar_alt', 'ss_do_sidebar_alt' );

    add_action( 'genesis_sidebar', 'my_custom_sidebar' );
    add_action( 'genesis_sidebar_alt', 'my_custom_sidebar_alt' );
    ~~~

    But this will not (because the main Genesis sidebar functions are also unhooked):

    ~~~php
    remove_action( 'genesis_sidebar', 'ss_do_sidebar' );
    remove_action( 'genesis_sidebar_alt', 'ss_do_sidebar_alt' );
    remove_action( 'genesis_sidebar', 'genesis_do_sidebar' );
    remove_action( 'genesis_sidebar_alt', 'genesis_do_sidebar_alt' );
    
    add_action( 'genesis_sidebar', 'my_custom_sidebar' );
    add_action( 'genesis_sidebar_alt', 'my_custom_sidebar_alt' );
    ~~~

    It's mostly Genesis Connect users who will be affected by this, so updating that before Simple Sidebars would likely help a lot: 

    https://github.com/search?p=1&q=%22remove_action%28+%27genesis_sidebar%27%2C+%27ss_do_sidebar%27%22&ref=searchresults&type=Code&utf8=%E2%9C%93

    Some snippets suggest removing the primary sidebar as well as Simple Sidebars, so they should be unaffected: 

   - https://gist.github.com/billerickson/5134811
   - https://gist.github.com/neilgee/4210a153a86e31f504ac

    But there are also snippets that advocate replacing `genesis_do_sidebar` removal with `ss_do_sidebar`, as Jen noted. For example:

    - https://gist.github.com/Lego2012/ee0832a06c56f756256f2e206ea11c46 (note “instead of”). 
    - https://gist.github.com/JiveDig/5550792

    Those are the users who will likely see doubled sidebars after the update.

2. Anyone who calls the `ss_` functions directly. Developers will see deprecation warnings, but plugins may lose functionality. I'm not sure what we can do about this except for leaving the `ss_` functions in place, or giving people more time to make updates.

**Comment by dreamwhisper** [comment] 2017-03-10 17:50
I'm going to dig out some of my old client themes and look what I did. I'm pretty sure they'll be broken too, but it has been awhile...

**Comment by nathanrice** [comment] 2017-03-10 19:42
Best I can tell, we're basically needing to account for the following scenarios:

1. If someone unhooks both Genesis default sidebar output, along with SS sidebar output.

In this scenario, we're covered. They're removing any change of double output but removing both actions.

2. If someone unhooks SS sidebar output, but leave Genesis sidebar output in place.

I can see how this would be logical. They assume SS removes the Genesis sidebar output, which it used to do. This way, they're covered whether or not SS is active, without having to do any conditional logic in their plugin.

In 6f8b1a2 I accounted for this by reusing the original hooked functions, but just making them dummy functions for the Genesis sidebar output. This way, unhooking the SS sidebar output continues to work as intended, because default sidebar output is tied to SS sidebar output (and filtered using the new method) as long as SS is active.

3. Genesis Connect does something a little different. It unhooks the SS sidebar (which does nothing if SS is inactive), looks for a special condition (the store page) and injects a custom sidebar by using a direct call to `dynamic_sidebar()`. But it then uses a fallback that calls `ss_do_one_sidebar()` for output and falls back to `ss_do_sidebar[_alt]()` if nothing happens.

So, this was the one that kept giving me issues. I think 6f8b1a2 addresses this too. I left it deprecated (rather than a dummy function), so that it would still function in unforseen uses, but at least it returns true when it does what it is intended to do. The notice still shows, so devs can know it's a deprecated function and remove it, but it won't break functionality.

This is not a "pure" solution, as the boilerplate code is now infected with legacy code, but I feel like it's totally worth it for how little actually needs to change to fix this problem. And I believe that all the old tutorials will still work, too. Though, new ones will need to be written, since we have a new method for swapping sidebars that is a bit more efficient, IMO.

Please test and let me know what you find.

**Comment by nickcernis** [comment] 2017-03-10 22:13
I like this approach and think leaving the old function names in place is a good compromise.

I can't break it so far:

- No more doubled sidebars with Genesis Connect active.
- Snippets that replace sidebars remove the sidebar if they unhook `ss_do_sidebar`, even if they don't also unhook `genesis_do_sidebar`.
- I still see deprecation warnings for use of `ss_do_one_sidebar()` with Genesis Connect active, but that seems fine given that it only appears if WP_DEBUG is on.

Wondering if we should pass the third parameter to `_deprecated_function` to give devs an idea of what they should be using instead of the deprecated `ss_` functions, but otherwise this seems ready to me. (The deprecation notice currently reads, “ss_do_one_sidebar is deprecated since version 2.1.0 with no alternative available.” Passing a string as a third param with replacement notes would get rid of 'no alternative available', which might be more helpful, unless there genuinely is no replacement option.)

**Comment by nathanrice** [comment] 2017-03-10 22:21
42315b2

It's a little more complicated than just suggesting a replacement function, but this is basically what you have to do.

I'll update Genesis Connect before pushing this out, so we lose the deprecation notice for most people, if they update both plugins.

**Comment by nathanrice** [comment] 2017-04-12 17:32
Actually, let's get this version out in the wild for a little bit before updating Genesis Connect. I want to make sure this penetrates the install base before updating the other plugin.

I'm fine with the deprecation notice showing in the mean time. If we get any support requests, just let them know what an update is forthcoming, and it will be fixed in the next release.

**Closed by nathanrice** 2017-04-12 17:32 UTC
Labels: Status: needs testing, Support: Blocker
